site_name: SCUTTLE Tech Guide
site_url: http://yoshiask.github.io/ScuttleTechGuide
repo_url: https://github.com/yoshiask/ScuttleTechGuide/
edit_uri: blob/main/docs

exclude_docs: |
  readme.md
  /_navbar.md
  /_sidebar.md

extra_css:
  - style.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - callouts
  - pagetree

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js