site_name: SCUTTLE Tech Guide
site_url: http://yoshiask.github.io/ScuttleTechGuide
repo_url: https://github.com/yoshiask/ScuttleTechGuide/
edit_uri: blob/main/docs

exclude_docs: |
  readme.md
  /_navbar.md
  /_sidebar.md

theme:
  name: material
  palette:
    scheme: scuttle

extra_css:
  - style.css

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - callouts
  - pagetree

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js