nav:
  - Home: index.md
  - Power: power.md
  - Computing: computing.md
  - Tools: tools.md
  - Wiring: wiring.md
  - Parts: parts.md
  - Boards:
    - BeagleY-AI: boards/beagley-ai
    - Raspberry Pi: boards/raspberry-pi
    - TI TDA4VM: boards/tda4vm
  - Brand: brand.md
  - Archive: archive.md